from app.models.user import User
from app.models.skill import Skill
from app.models.course import Course
from app.models.user_skill import UserSkill
from app.models.course_skill import CourseSkill
from app.models.prerequisite import CoursePrerequisite
from app.models.learning_history import LearningHistory
from app.models.feedback import LearningFeedback
from app.models.user_interest import UserInterest